layout_spectrum: 0.4968650483060628
typography_spectrum: 0.34576411452144384
color:
  brandStrength: 0.9893912503030151
  lightness: 0.6144061705563217
  saturation: 0.8165950938127935
  rhythmicContrast: 0.2751048260834068
  brandColors:
    - '#FF5335'
    - '#B39C85'
    - '#306E73'
    - '#3B424D'
    - '#1D181F'
name: Anders Haaber
navigation:
  - id: 05b4855b-69f9-4f1e-9cc5-ac871f7e01fc
    url: 2016-07-21-05b4855b-69f9-4f1e-9cc5-ac871f7e01fc.html
    name: MUSIKER
    type: content
